import type { Config } from "tailwindcss"

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
    },
    fontFamily: {
      sans: [
        "-apple-system",
        "BlinkMacSystemFont",
        "avenir next",
        "avenir",
        "segoe ui",
        "helvetica neue",
        "helvetica",
        "Cantarell",
        "Ubuntu",
        "roboto",
        "noto",
        "arial",
        "sans-serif",
      ],
      serif: [
        "Iowan Old Style",
        "Apple Garamond",
        "Baskerville",
        "Times New Roman",
        "Droid Serif",
        "Times",
        "Surce Serif Pro",
        "serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
      ],
      mono: [
        "Menlo",
        "Consolas",
        "Liberation Mono",
        "Lucida Console",
        "monospace",
      ],
    },
    screens: {
      sm: "420px",
      md: "820px",
      lg: "1250px",
      xl: "1250px",
    },
    colors: {
      black: "#000000",
      white: "#FFFFFF",
      blue: "#ABB2FF",
      pink: "#EEA3A0",
      peach: "#FEEFE3",
      orange: "#FFA852",
      yellow: "#FFD974",
      gray: "#A9A9A9",
      red: "#FF0202",
    },
    extend: {},
  },
  plugins: [],
} satisfies Config
